INSERT INTO `gen_languages` VALUES (1, 'Hindi', '39.29%');
INSERT INTO `gen_languages` VALUES (2, 'Bengali', '8.30%');
INSERT INTO `gen_languages` VALUES (3, 'Telugu', '7.87%');
INSERT INTO `gen_languages` VALUES (4, 'Marathi', '7.45%');
INSERT INTO `gen_languages` VALUES (5, 'Tamil', '6.32%');
INSERT INTO `gen_languages` VALUES (6, 'Urdu', '5.18%');
INSERT INTO `gen_languages` VALUES (7, 'Kannada', '3.91%');
INSERT INTO `gen_languages` VALUES (8, 'Malayalam', '3.62%');
INSERT INTO `gen_languages` VALUES (9, 'Oriya', '4.85%');
INSERT INTO `gen_languages` VALUES (10, 'Gujarati', '3.35%');
INSERT INTO `gen_languages` VALUES (11, 'Punjabi', '2.79%');
INSERT INTO `gen_languages` VALUES (12, 'Assamese', '1.56%');
INSERT INTO `gen_languages` VALUES (13, 'Maithili', '0.926%');
INSERT INTO `gen_languages` VALUES (14, 'Bhili/Bhilodi', 'Bhili/Bhilodi');
INSERT INTO `gen_languages` VALUES (15, 'Santali', 'Santali');
INSERT INTO `gen_languages` VALUES (16, 'Kashmiri', 'Kashmiri');
INSERT INTO `gen_languages` VALUES (17, 'Nepali', 'Nepali');
INSERT INTO `gen_languages` VALUES (18, 'Gondi', 'Gondi');
INSERT INTO `gen_languages` VALUES (19, 'Sindhi', 'Sindhi');
INSERT INTO `gen_languages` VALUES (20, 'Konkani', 'Konkani');
INSERT INTO `gen_languages` VALUES (21, 'Dogri', 'Dogri');
INSERT INTO `gen_languages` VALUES (22, 'Khandeshi', 'Khandeshi');
INSERT INTO `gen_languages` VALUES (23, 'Kurukh', 'Kurukh');
INSERT INTO `gen_languages` VALUES (24, 'Tulu', 'Tulu');
INSERT INTO `gen_languages` VALUES (25, 'Meitei/Manipuri', 'Meitei/Manipuri');
INSERT INTO `gen_languages` VALUES (26, 'Bodo', 'Bodo');
INSERT INTO `gen_languages` VALUES (27, 'Khasi', 'Khasi');
INSERT INTO `gen_languages` VALUES (28, 'Mundari', 'Mundari');
INSERT INTO `gen_languages` VALUES (29, 'Ho', 'Ho');
INSERT INTO `gen_languages` VALUES (30,'Kui','Kui');
INSERT INTO `gen_languages` VALUES (31,'Garo','Garo');
INSERT INTO `gen_languages` VALUES (32,'Kokborok','Kokborok');
INSERT INTO `gen_languages` VALUES (33,'Mizo','Mizo');
INSERT INTO `gen_languages` VALUES (34,'Halabi','Halabi');
INSERT INTO `gen_languages` VALUES (35,'Korku','Korku');
INSERT INTO `gen_languages` VALUES (36,'Munda','Munda');
INSERT INTO `gen_languages` VALUES (37,'Mishing','Mishing');
INSERT INTO `gen_languages` VALUES (38,'Karbi/Mikir','Karbi/Mikir');
INSERT INTO `gen_languages` VALUES (39,'Saurashtra','Saurashtra');
INSERT INTO `gen_languages` VALUES (40,'Savara','Savara');
INSERT INTO `gen_languages` VALUES (41,'Koya','Koya');
INSERT INTO `gen_languages` VALUES (42,'English','English');
INSERT INTO `gen_languages` VALUES (43,'Kharia','Kharia');
INSERT INTO `gen_languages` VALUES (44,'Khond/Kondh','Khond/Kondh');
INSERT INTO `gen_languages` VALUES (45,'Nishi','Nishi');
INSERT INTO `gen_languages` VALUES (46,'Ao','Ao');
INSERT INTO `gen_languages` VALUES (50,'Sema','Sema');
INSERT INTO `gen_languages` VALUES (51,'Kisan','Kisan');
INSERT INTO `gen_languages` VALUES (52,'Adi','Adi');
INSERT INTO `gen_languages` VALUES (53,'Rabha','Rabha');
INSERT INTO `gen_languages` VALUES (54,'Konyak','Konyak');
INSERT INTO `gen_languages` VALUES (55,'Malto','Malto');
INSERT INTO `gen_languages` VALUES (56,'Thado','Thado');
INSERT INTO `gen_languages` VALUES (57,'Tangkhul','Tangkhul');
